/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "HHH",
  "description": "LLL",
  "base": "/docs/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/docs/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "HJJ"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vue[ress介绍，啥啥啥"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0884fec0",
      "path": "/",
      "lastUpdated": "2022-04-22 6:29:25",
      "lastUpdatedTimestamp": 1650623365000
    },
    {
      "title": "about,",
      "frontmatter": {
        "title": "about,"
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-2622b951",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-22 6:29:25",
      "lastUpdatedTimestamp": 1650623365000
    },
    {
      "title": "about---a",
      "frontmatter": {
        "title": "about---a"
      },
      "regularPath": "/about/a.html",
      "relativePath": "about/a.md",
      "key": "v-4a8db2ce",
      "path": "/about/a.html",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-22 6:29:25",
      "lastUpdatedTimestamp": 1650623365000
    },
    {
      "title": "about---b",
      "frontmatter": {
        "title": "about---b"
      },
      "regularPath": "/about/bbb.html",
      "relativePath": "about/bbb.md",
      "key": "v-21b8316e",
      "path": "/about/bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-22 6:29:25",
      "lastUpdatedTimestamp": 1650623365000
    },
    {
      "title": "about2",
      "frontmatter": {
        "title": "about2"
      },
      "regularPath": "/about2.html",
      "relativePath": "about2.md",
      "key": "v-091460c6",
      "path": "/about2.html",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-22 6:29:25",
      "lastUpdatedTimestamp": 1650623365000
    },
    {
      "title": "about1",
      "frontmatter": {
        "title": "about1"
      },
      "regularPath": "/about1.html",
      "relativePath": "about1.md",
      "key": "v-182f191f",
      "path": "/about1.html",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-22 6:29:25",
      "lastUpdatedTimestamp": 1650623365000
    },
    {
      "title": "about---c",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "a",
        "7": "b",
        "8": "o",
        "9": "u",
        "10": "t",
        "11": "-",
        "12": "-",
        "13": "-",
        "14": "c"
      },
      "regularPath": "/about/c.html",
      "relativePath": "about/c.md",
      "key": "v-2169bfe4",
      "path": "/about/c.html",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-22 6:29:25",
      "lastUpdatedTimestamp": 1650623365000
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "aboout",
        "link": "/about/",
        "target": "_blank",
        "rel": ""
      },
      {
        "text": "my",
        "link": "https://google.com"
      }
    ],
    "sidebar": [
      "",
      "/about2",
      "/about1",
      {
        "title": "Group about",
        "path": "/about/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/about/",
          "/about/a",
          "/about/bbb",
          "/about/c"
        ]
      }
    ]
  }
}