/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "HHH",
  "description": "LLL",
  "base": "/docs/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/docs/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "HJJ"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vue[ress介绍，啥啥啥"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/docs/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/docs/icons/apple-touch-icon-152x152.png"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/docs/icons/safari-pinned-tab.svg",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/icons/msapplication-icon-144x144.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ],
    [
      "script",
      {
        "async": "true",
        "src": "https://www.googletagmanager.com/gtag/js?id=G-1CB2FVSC68"
      }
    ],
    [
      "script",
      {},
      "\n            window.dataLayer = window.dataLayer || [];\n            function gtag(){dataLayer.push(arguments);}\n            gtag('js', new Date());\n            gtag('config', 'G-1CB2FVSC68');"
    ]
  ],
  "pages": [
    {
      "title": "移动端适配谷朊粉",
      "frontmatter": {},
      "regularPath": "/05-css/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html",
      "relativePath": "05-css/DIV水平垂直居中/大屏适配方案.md",
      "key": "v-2d1785d8",
      "path": "/05-css/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html"
    },
    {
      "title": "about,",
      "frontmatter": {
        "title": "about,"
      },
      "regularPath": "/05-css/",
      "relativePath": "05-css/README.md",
      "key": "v-0ab70fcc",
      "path": "/05-css/",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ]
    },
    {
      "title": "CSS常见技巧汇总",
      "frontmatter": {},
      "regularPath": "/05-css/CSS%E9%AB%98%E7%BA%A7%E5%B8%B8%E8%A7%81%E6%8A%80%E5%B7%A7%E6%B1%87%E6%80%BB.html",
      "relativePath": "05-css/CSS高级常见技巧汇总.md",
      "key": "v-2a5228f4",
      "path": "/05-css/CSS%E9%AB%98%E7%BA%A7%E5%B8%B8%E8%A7%81%E6%8A%80%E5%B7%A7%E6%B1%87%E6%80%BB.html",
      "headers": [
        {
          "level": 2,
          "title": "1、设置input",
          "slug": "_1、设置input"
        },
        {
          "level": 2,
          "title": "2、单行和多行文本超出省略号",
          "slug": "_2、单行和多行文本超出省略号"
        },
        {
          "level": 2,
          "title": "3、负边距使用技巧",
          "slug": "_3、负边距使用技巧"
        },
        {
          "level": 2,
          "title": "4、outline属性的妙用技巧",
          "slug": "_4、outline属性的妙用技巧"
        },
        {
          "level": 2,
          "title": "5、虚线框绘制技巧",
          "slug": "_5、虚线框绘制技巧"
        },
        {
          "level": 2,
          "title": "6、隐藏文本的常用两种方法",
          "slug": "_6、隐藏文本的常用两种方法"
        },
        {
          "level": 2,
          "title": "7、表格",
          "slug": "_7、表格"
        },
        {
          "level": 2,
          "title": "8、卡券效果制作",
          "slug": "_8、卡券效果制作"
        }
      ]
    },
    {
      "title": "解决移动端 Retina 屏幕 1px 边框问题",
      "frontmatter": {},
      "regularPath": "/05-css/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html",
      "relativePath": "05-css/DIV水平垂直居中/retina屏幕1px边框问题.md",
      "key": "v-ae43d944",
      "path": "/05-css/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html",
      "headers": [
        {
          "level": 2,
          "title": "一、概念",
          "slug": "一、概念"
        },
        {
          "level": 2,
          "title": "二、造成边框变粗的原因",
          "slug": "二、造成边框变粗的原因"
        },
        {
          "level": 2,
          "title": "三、解决边框变粗的8种办法",
          "slug": "三、解决边框变粗的8种办法"
        },
        {
          "level": 3,
          "title": "1、0.5px边框",
          "slug": "_1、0-5px边框"
        },
        {
          "level": 3,
          "title": "2、border-image",
          "slug": "_2、border-image"
        },
        {
          "level": 3,
          "title": "3、background-image",
          "slug": "_3、background-image"
        },
        {
          "level": 3,
          "title": "4、多背景渐变实现",
          "slug": "_4、多背景渐变实现"
        },
        {
          "level": 3,
          "title": "5、使用box-shadow模拟边框",
          "slug": "_5、使用box-shadow模拟边框"
        },
        {
          "level": 3,
          "title": "6、viewport + rem",
          "slug": "_6、viewport-rem"
        },
        {
          "level": 3,
          "title": "7、伪类 + transform",
          "slug": "_7、伪类-transform"
        },
        {
          "level": 3,
          "title": "8、svg",
          "slug": "_8、svg"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        }
      ]
    },
    {
      "title": "移动端适配谷朊粉",
      "frontmatter": {},
      "regularPath": "/05-css/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html",
      "relativePath": "05-css/大屏适配方案.md",
      "key": "v-27cf6b54",
      "path": "/05-css/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html"
    },
    {
      "title": "移动端适配谷朊粉",
      "frontmatter": {},
      "regularPath": "/05-css/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88%20-%20%E5%89%AF%E6%9C%AC.html",
      "relativePath": "05-css/移动端适配方案 - 副本.md",
      "key": "v-1703a073",
      "path": "/05-css/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88%20-%20%E5%89%AF%E6%9C%AC.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/05-css/%E8%AE%BE%E7%BD%AEinput.html",
      "relativePath": "05-css/设置input.md",
      "key": "v-3923b5ba",
      "path": "/05-css/%E8%AE%BE%E7%BD%AEinput.html"
    },
    {
      "title": "css 绘制三角形",
      "frontmatter": {},
      "regularPath": "/05-css/css%20%E5%AE%9E%E7%8E%B0%E4%B8%8A%E5%8F%B3%E4%B8%8B%E5%B7%A6%E4%B8%89%E8%A7%92.html",
      "relativePath": "05-css/css 实现上右下左三角.md",
      "key": "v-2b825978",
      "path": "/05-css/css%20%E5%AE%9E%E7%8E%B0%E4%B8%8A%E5%8F%B3%E4%B8%8B%E5%B7%A6%E4%B8%89%E8%A7%92.html",
      "headers": [
        {
          "level": 2,
          "title": "右三角",
          "slug": "右三角"
        },
        {
          "level": 2,
          "title": "左三角",
          "slug": "左三角"
        },
        {
          "level": 2,
          "title": "下三角",
          "slug": "下三角"
        },
        {
          "level": 2,
          "title": "上三角",
          "slug": "上三角"
        }
      ]
    },
    {
      "title": "隐藏滚动条或更改滚动条样式",
      "frontmatter": {},
      "regularPath": "/05-css/%E9%9A%90%E8%97%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%88%96%E6%9B%B4%E6%94%B9%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%A0%B7%E5%BC%8F.html",
      "relativePath": "05-css/隐藏滚动条或更改滚动条样式.md",
      "key": "v-af205296",
      "path": "/05-css/%E9%9A%90%E8%97%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%88%96%E6%9B%B4%E6%94%B9%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%A0%B7%E5%BC%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "隐藏滚动条或更改滚动条样式",
          "slug": "隐藏滚动条或更改滚动条样式"
        }
      ]
    },
    {
      "title": "解决移动端 Retina 屏幕 1px 边框问题",
      "frontmatter": {},
      "regularPath": "/05-css/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html",
      "relativePath": "05-css/retina屏幕1px边框问题.md",
      "key": "v-17b1b6fe",
      "path": "/05-css/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html",
      "headers": [
        {
          "level": 2,
          "title": "一、概念",
          "slug": "一、概念"
        },
        {
          "level": 2,
          "title": "二、造成边框变粗的原因",
          "slug": "二、造成边框变粗的原因"
        },
        {
          "level": 2,
          "title": "三、解决边框变粗的8种办法",
          "slug": "三、解决边框变粗的8种办法"
        },
        {
          "level": 3,
          "title": "1、0.5px边框",
          "slug": "_1、0-5px边框"
        },
        {
          "level": 3,
          "title": "2、border-image",
          "slug": "_2、border-image"
        },
        {
          "level": 3,
          "title": "3、background-image",
          "slug": "_3、background-image"
        },
        {
          "level": 3,
          "title": "4、多背景渐变实现",
          "slug": "_4、多背景渐变实现"
        },
        {
          "level": 3,
          "title": "5、使用box-shadow模拟边框",
          "slug": "_5、使用box-shadow模拟边框"
        },
        {
          "level": 3,
          "title": "6、viewport + rem",
          "slug": "_6、viewport-rem"
        },
        {
          "level": 3,
          "title": "7、伪类 + transform",
          "slug": "_7、伪类-transform"
        },
        {
          "level": 3,
          "title": "8、svg",
          "slug": "_8、svg"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        }
      ]
    },
    {
      "title": "兼容性",
      "frontmatter": {},
      "regularPath": "/06-js/00-es6/es6.html",
      "relativePath": "06-js/00-es6/es6.md",
      "key": "v-1265eb6c",
      "path": "/06-js/00-es6/es6.html",
      "headers": [
        {
          "level": 2,
          "title": "兼容性",
          "slug": "兼容性"
        },
        {
          "level": 2,
          "title": "let和const",
          "slug": "let和const"
        },
        {
          "level": 2,
          "title": "解构赋值",
          "slug": "解构赋值"
        },
        {
          "level": 2,
          "title": "字符串",
          "slug": "字符串"
        },
        {
          "level": 2,
          "title": "json",
          "slug": "json"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ]
    },
    {
      "title": "es6函数-箭头函数",
      "frontmatter": {},
      "regularPath": "/06-js/00-es6/es6%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0.html",
      "relativePath": "06-js/00-es6/es6箭头函数.md",
      "key": "v-74e177e2",
      "path": "/06-js/00-es6/es6%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "es6函数-箭头函数",
          "slug": "es6函数-箭头函数"
        },
        {
          "level": 3,
          "title": "一、写法",
          "slug": "一、写法"
        },
        {
          "level": 3,
          "title": "二、特点",
          "slug": "二、特点"
        }
      ]
    },
    {
      "title": "async",
      "frontmatter": {},
      "regularPath": "/06-js/00-es6/async%E5%87%BD%E6%95%B0.html",
      "relativePath": "06-js/00-es6/async函数.md",
      "key": "v-0d99763f",
      "path": "/06-js/00-es6/async%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "一、基本使用",
          "slug": "一、基本使用"
        },
        {
          "level": 3,
          "title": "返回值",
          "slug": "返回值"
        },
        {
          "level": 3,
          "title": "await 表达式",
          "slug": "await-表达式"
        },
        {
          "level": 3,
          "title": "应用",
          "slug": "应用"
        },
        {
          "level": 2,
          "title": "二、async 函数的优点",
          "slug": "二、async-函数的优点"
        },
        {
          "level": 3,
          "title": "2.1.对比于Generator",
          "slug": "_2-1-对比于generator"
        },
        {
          "level": 3,
          "title": "2.2.对比于Promise",
          "slug": "_2-2-对比于promise"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "内置对象",
      "frontmatter": {},
      "regularPath": "/06-js/js%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1.html",
      "relativePath": "06-js/js内置对象.md",
      "key": "v-56416e0b",
      "path": "/06-js/js%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1.html",
      "headers": [
        {
          "level": 2,
          "title": "内置对象",
          "slug": "内置对象"
        },
        {
          "level": 3,
          "title": "Math对象",
          "slug": "math对象"
        },
        {
          "level": 3,
          "title": "Date对象",
          "slug": "date对象"
        },
        {
          "level": 3,
          "title": "Array对象",
          "slug": "array对象"
        },
        {
          "level": 3,
          "title": "正则表达式对象",
          "slug": "正则表达式对象"
        },
        {
          "level": 3,
          "title": "String对象",
          "slug": "string对象"
        }
      ]
    },
    {
      "title": "JS中的数据类型",
      "frontmatter": {},
      "regularPath": "/06-js/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html",
      "relativePath": "06-js/js数据类型.md",
      "key": "v-0555ccf4",
      "path": "/06-js/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "一、JS中的数据类型",
          "slug": "一、js中的数据类型"
        },
        {
          "level": 3,
          "title": "1.1.基本类型（值类型）",
          "slug": "_1-1-基本类型-值类型"
        },
        {
          "level": 3,
          "title": "1.2.复杂类型（引用类型）",
          "slug": "_1-2-复杂类型-引用类型"
        },
        {
          "level": 3,
          "title": "1.3.堆和栈",
          "slug": "_1-3-堆和栈"
        },
        {
          "level": 2,
          "title": "二、JS类型检测方式",
          "slug": "二、js类型检测方式"
        },
        {
          "level": 3,
          "title": "2.1.typeof：主要用于检测基本类型",
          "slug": "_2-1-typeof-主要用于检测基本类型"
        },
        {
          "level": 3,
          "title": "2.2.instanceof：主要用于检测引用类型",
          "slug": "_2-2-instanceof-主要用于检测引用类型"
        },
        {
          "level": 3,
          "title": "2.3.Object.prototype.toString.call()：",
          "slug": "_2-3-object-prototype-tostring-call"
        },
        {
          "level": 2,
          "title": "三、值类型和引用类型在内存中的存储方式",
          "slug": "三、值类型和引用类型在内存中的存储方式"
        },
        {
          "level": 2,
          "title": "四、值类型复制和引用类型复制",
          "slug": "四、值类型复制和引用类型复制"
        },
        {
          "level": 3,
          "title": "4.1.深拷贝和浅拷贝",
          "slug": "_4-1-深拷贝和浅拷贝"
        },
        {
          "level": 2,
          "title": "五、值类型和引用类型参数传递",
          "slug": "五、值类型和引用类型参数传递"
        },
        {
          "level": 2,
          "title": "六、值类型与引用类型的差别",
          "slug": "六、值类型与引用类型的差别"
        },
        {
          "level": 2,
          "title": "七、数据类型转换",
          "slug": "七、数据类型转换"
        },
        {
          "level": 3,
          "title": "7.1.转换成字符串类型",
          "slug": "_7-1-转换成字符串类型"
        },
        {
          "level": 3,
          "title": "7.2.转换成数值类型",
          "slug": "_7-2-转换成数值类型"
        },
        {
          "level": 3,
          "title": "7.3.转换成布尔类型",
          "slug": "_7-3-转换成布尔类型"
        }
      ]
    },
    {
      "title": "about,",
      "frontmatter": {
        "title": "about,"
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-27bd8008",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-22 10:22:56",
      "lastUpdatedTimestamp": 1650637376000,
      "createdTime": 1650637376000
    },
    {
      "title": "about---b",
      "frontmatter": {
        "title": "about---b"
      },
      "regularPath": "/about/bbb.html",
      "relativePath": "about/bbb.md",
      "key": "v-28300517",
      "path": "/about/bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-22 10:22:56",
      "lastUpdatedTimestamp": 1650637376000,
      "createdTime": 1650637376000
    },
    {
      "title": "about---c",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "a",
        "7": "b",
        "8": "o",
        "9": "u",
        "10": "t",
        "11": "-",
        "12": "-",
        "13": "-",
        "14": "c"
      },
      "regularPath": "/about/c.html",
      "relativePath": "about/c.md",
      "key": "v-21093037",
      "path": "/about/c.html",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-22 10:22:56",
      "lastUpdatedTimestamp": 1650637376000,
      "createdTime": 1650637376000
    },
    {
      "title": "about---a",
      "frontmatter": {
        "title": "about---a"
      },
      "regularPath": "/about/a.html",
      "relativePath": "about/a.md",
      "key": "v-7c4bc2f7",
      "path": "/about/a.html",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-22 10:22:56",
      "lastUpdatedTimestamp": 1650637376000,
      "createdTime": 1650637376000
    },
    {
      "title": "about1",
      "frontmatter": {
        "title": "about1"
      },
      "regularPath": "/about1.html",
      "relativePath": "about1.md",
      "key": "v-7b551f88",
      "path": "/about1.html",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html 哈哈哈哈哈哈",
          "slug": "标题1-html-哈哈哈哈哈哈"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        }
      ],
      "lastUpdated": "2022-04-25 10:04:44",
      "lastUpdatedTimestamp": 1650852284000,
      "createdTime": 1650637376000
    },
    {
      "title": "countup 第三方组件",
      "frontmatter": {
        "titlt": "countup第三方组件"
      },
      "regularPath": "/countup.html",
      "relativePath": "countup.md",
      "key": "v-b9876738",
      "path": "/countup.html",
      "headers": [
        {
          "level": 2,
          "title": "追加Travis Cli 自动化",
          "slug": "追加travis-cli-自动化"
        }
      ],
      "lastUpdated": "2022-04-24 5:04:46",
      "lastUpdatedTimestamp": 1650791086000,
      "createdTime": 1650791086000
    },
    {
      "title": "about2",
      "frontmatter": {
        "title": "about2"
      },
      "regularPath": "/about2.html",
      "relativePath": "about2.md",
      "key": "v-5e9bd606",
      "path": "/about2.html",
      "headers": [
        {
          "level": 2,
          "title": "标题1.html",
          "slug": "标题1-html"
        },
        {
          "level": 2,
          "title": "标题2.html",
          "slug": "标题2-html"
        },
        {
          "level": 2,
          "title": "github action",
          "slug": "github-action"
        }
      ],
      "lastUpdated": "2022-04-24 9:09:19",
      "lastUpdatedTimestamp": 1650805759000,
      "createdTime": 1650637376000
    },
    {
      "title": "很长的文章啊",
      "frontmatter": {
        "title": "很长的文章啊"
      },
      "regularPath": "/article.html",
      "relativePath": "article.md",
      "key": "v-07c3fbe4",
      "path": "/article.html",
      "headers": [
        {
          "level": 2,
          "title": "一、CSS",
          "slug": "一、css"
        },
        {
          "level": 3,
          "title": "1、移动端1px 解决方案",
          "slug": "_1、移动端1px-解决方案"
        },
        {
          "level": 3,
          "title": "2、opacity_visibility_display优劣",
          "slug": "_2、opacity-visibility-display优劣"
        },
        {
          "level": 3,
          "title": "3、盒模型介绍",
          "slug": "_3、盒模型介绍"
        },
        {
          "level": 3,
          "title": "4、css 选择器和优先级",
          "slug": "_4、css-选择器和优先级"
        },
        {
          "level": 3,
          "title": "5、flex",
          "slug": "_5、flex"
        },
        {
          "level": 3,
          "title": "6、line-height 如何继承？",
          "slug": "_6、line-height-如何继承"
        },
        {
          "level": 3,
          "title": "7、水平垂直居中",
          "slug": "_7、水平垂直居中"
        },
        {
          "level": 3,
          "title": "8、文档流",
          "slug": "_8、文档流"
        },
        {
          "level": 3,
          "title": "9、BFC的形成和作用",
          "slug": "_9、bfc的形成和作用"
        },
        {
          "level": 3,
          "title": "10、CSS预处理器",
          "slug": "_10、css预处理器"
        },
        {
          "level": 3,
          "title": "11、em、rem、px",
          "slug": "_11、em、rem、px"
        },
        {
          "level": 3,
          "title": "12、父子边距重合",
          "slug": "_12、父子边距重合"
        },
        {
          "level": 3,
          "title": "13、padding、margin百分比单位参考的依据",
          "slug": "_13、padding、margin百分比单位参考的依据"
        },
        {
          "level": 3,
          "title": "14、清除浮动",
          "slug": "_14、清除浮动"
        },
        {
          "level": 2,
          "title": "二、html",
          "slug": "二、html"
        },
        {
          "level": 3,
          "title": "1、列出常见的行内元素、块级元素、空(void)元素？",
          "slug": "_1、列出常见的行内元素、块级元素、空-void-元素"
        },
        {
          "level": 3,
          "title": "2、DIV元素垂直居中",
          "slug": "_2、div元素垂直居中"
        },
        {
          "level": 3,
          "title": "3、如何理解 HTML 语义化？",
          "slug": "_3、如何理解-html-语义化"
        },
        {
          "level": 3,
          "title": "4、script 标签中 defer 和 async 的区别？",
          "slug": "_4、script-标签中-defer-和-async-的区别"
        },
        {
          "level": 3,
          "title": "5、iframe的优点、缺点",
          "slug": "_5、iframe的优点、缺点"
        },
        {
          "level": 2,
          "title": "三、js",
          "slug": "三、js"
        },
        {
          "level": 3,
          "title": "1、this指向问题",
          "slug": "_1、this指向问题"
        },
        {
          "level": 3,
          "title": "2、什么时候用箭头函数",
          "slug": "_2、什么时候用箭头函数"
        },
        {
          "level": 3,
          "title": "3、call、apply、bind有什么区别？",
          "slug": "_3、call、apply、bind有什么区别"
        },
        {
          "level": 3,
          "title": "4、改变this的指向",
          "slug": "_4、改变this的指向"
        },
        {
          "level": 3,
          "title": "5、基础的数据类型有哪几种",
          "slug": "_5、基础的数据类型有哪几种"
        },
        {
          "level": 3,
          "title": "6、值类型和引用类型的理解",
          "slug": "_6、值类型和引用类型的理解"
        },
        {
          "level": 3,
          "title": "7、数据类型的判断",
          "slug": "_7、数据类型的判断"
        },
        {
          "level": 3,
          "title": "8、如何判断变量是否为数组",
          "slug": "_8、如何判断变量是否为数组"
        },
        {
          "level": 3,
          "title": "9、JavaScript数字精度丢失问题",
          "slug": "_9、javascript数字精度丢失问题"
        },
        {
          "level": 3,
          "title": "10、深拷贝、浅拷贝",
          "slug": "_10、深拷贝、浅拷贝"
        },
        {
          "level": 3,
          "title": "11、创建对象的方式",
          "slug": "_11、创建对象的方式"
        },
        {
          "level": 3,
          "title": "12、构造函数",
          "slug": "_12、构造函数"
        },
        {
          "level": 3,
          "title": "13、new关键字",
          "slug": "_13、new关键字"
        },
        {
          "level": 3,
          "title": "14、原型和原型链",
          "slug": "_14、原型和原型链"
        },
        {
          "level": 3,
          "title": "15、作用域与作用域链",
          "slug": "_15、作用域与作用域链"
        },
        {
          "level": 3,
          "title": "16、词法作用域",
          "slug": "_16、词法作用域"
        },
        {
          "level": 3,
          "title": "17、闭包",
          "slug": "_17、闭包"
        },
        {
          "level": 3,
          "title": "18、call、apply、bind 实现原理",
          "slug": "_18、call、apply、bind-实现原理"
        },
        {
          "level": 3,
          "title": "19、数组的方法",
          "slug": "_19、数组的方法"
        },
        {
          "level": 3,
          "title": "20、数组响应式方法",
          "slug": "_20、数组响应式方法"
        },
        {
          "level": 3,
          "title": "21、数组去重",
          "slug": "_21、数组去重"
        },
        {
          "level": 3,
          "title": "22、字符串的方法",
          "slug": "_22、字符串的方法"
        },
        {
          "level": 3,
          "title": "23、内置对象-Math",
          "slug": "_23、内置对象-math"
        },
        {
          "level": 3,
          "title": "24、内置对象-Date",
          "slug": "_24、内置对象-date"
        },
        {
          "level": 3,
          "title": "25、正则",
          "slug": "_25、正则"
        },
        {
          "level": 2,
          "title": "四、Web API",
          "slug": "四、web-api"
        },
        {
          "level": 3,
          "title": "1、页面加载事件",
          "slug": "_1、页面加载事件"
        },
        {
          "level": 3,
          "title": "2、location对象",
          "slug": "_2、location对象"
        },
        {
          "level": 3,
          "title": "3、history对象",
          "slug": "_3、history对象"
        },
        {
          "level": 3,
          "title": "4、navigator对象",
          "slug": "_4、navigator对象"
        },
        {
          "level": 2,
          "title": "五、ES6",
          "slug": "五、es6"
        },
        {
          "level": 3,
          "title": "async/await 和 Promise 的关系",
          "slug": "async-await-和-promise-的关系"
        },
        {
          "level": 3,
          "title": "Set、WeakSet和Map、WeakMap的区别",
          "slug": "set、weakset和map、weakmap的区别"
        },
        {
          "level": 2,
          "title": "六、jQuery",
          "slug": "六、jquery"
        },
        {
          "level": 2,
          "title": "七、编程算法",
          "slug": "七、编程算法"
        },
        {
          "level": 3,
          "title": "10、instanceof",
          "slug": "_10、instanceof"
        },
        {
          "level": 3,
          "title": "11、数组扁平化",
          "slug": "_11、数组扁平化"
        },
        {
          "level": 3,
          "title": "12、手写Promise/A",
          "slug": "_12、手写promise-a"
        },
        {
          "level": 3,
          "title": "13、使用Promise实现每隔1秒输出1,2,3",
          "slug": "_13、使用promise实现每隔1秒输出1-2-3"
        },
        {
          "level": 3,
          "title": "14、使用Promise实现红绿灯交替重复亮",
          "slug": "_14、使用promise实现红绿灯交替重复亮"
        },
        {
          "level": 3,
          "title": "15、 实现mergePromise函数",
          "slug": "_15、-实现mergepromise函数"
        },
        {
          "level": 3,
          "title": "16、封装一个异步加载图片的方法",
          "slug": "_16、封装一个异步加载图片的方法"
        },
        {
          "level": 3,
          "title": "17、限制异步操作的并发个数并尽可能快的完成全部",
          "slug": "_17、限制异步操作的并发个数并尽可能快的完成全部"
        },
        {
          "level": 3,
          "title": "18、实现一个 Promise.all",
          "slug": "_18、实现一个-promise-all"
        },
        {
          "level": 2,
          "title": "八、浏览器",
          "slug": "八、浏览器"
        },
        {
          "level": 3,
          "title": "1、从浏览器地址栏输入 url 到请求返回发生了什么",
          "slug": "_1、从浏览器地址栏输入-url-到请求返回发生了什么"
        },
        {
          "level": 3,
          "title": "2、TCP三次握手",
          "slug": "_2、tcp三次握手"
        },
        {
          "level": 3,
          "title": "3、TCP四次挥手",
          "slug": "_3、tcp四次挥手"
        },
        {
          "level": 3,
          "title": "4、浏览器渲染机制？",
          "slug": "_4、浏览器渲染机制"
        },
        {
          "level": 3,
          "title": "5、重排（reflow）和重绘（repaint）的理解",
          "slug": "_5、重排-reflow-和重绘-repaint-的理解"
        },
        {
          "level": 3,
          "title": "6、如何做好不频繁触发浏览器的回流与重绘？",
          "slug": "_6、如何做好不频繁触发浏览器的回流与重绘"
        },
        {
          "level": 3,
          "title": "7、浏览器内核（渲染引擎）",
          "slug": "_7、浏览器内核-渲染引擎"
        },
        {
          "level": 3,
          "title": "8、Event Loop",
          "slug": "_8、event-loop"
        },
        {
          "level": 3,
          "title": "9、浏览器的垃圾回收机制(GC)",
          "slug": "_9、浏览器的垃圾回收机制-gc"
        },
        {
          "level": 3,
          "title": "10、内存泄漏",
          "slug": "_10、内存泄漏"
        },
        {
          "level": 2,
          "title": "九、web存储",
          "slug": "九、web存储"
        },
        {
          "level": 3,
          "title": "1、cookie",
          "slug": "_1、cookie"
        },
        {
          "level": 3,
          "title": "2、session",
          "slug": "_2、session"
        },
        {
          "level": 3,
          "title": "3、localStorage 和 sessionStorage",
          "slug": "_3、localstorage-和-sessionstorage"
        },
        {
          "level": 2,
          "title": "十、Http",
          "slug": "十、http"
        },
        {
          "level": 3,
          "title": "1、http 状态码",
          "slug": "_1、http-状态码"
        },
        {
          "level": 3,
          "title": "2、http 缓存",
          "slug": "_2、http-缓存"
        },
        {
          "level": 3,
          "title": "3、 GET 和 POST 的区别。",
          "slug": "_3、-get-和-post-的区别。"
        },
        {
          "level": 3,
          "title": "4、HTTP/2 有哪些改进？（很大可能问原理）",
          "slug": "_4、http-2-有哪些改进-很大可能问原理"
        },
        {
          "level": 3,
          "title": "5、跨域问题",
          "slug": "_5、跨域问题"
        },
        {
          "level": 3,
          "title": "6、Token-- 服务端身份验证的流行方案",
          "slug": "_6、token-服务端身份验证的流行方案"
        },
        {
          "level": 3,
          "title": "7、前端埋点",
          "slug": "_7、前端埋点"
        },
        {
          "level": 3,
          "title": "8、每个页面需要计算浏览轨迹，怎么实现",
          "slug": "_8、每个页面需要计算浏览轨迹-怎么实现"
        },
        {
          "level": 2,
          "title": "前端安全问题",
          "slug": "前端安全问题"
        },
        {
          "level": 3,
          "title": "",
          "slug": ""
        },
        {
          "level": 2,
          "title": "兼容问题",
          "slug": "兼容问题"
        },
        {
          "level": 2,
          "title": "适配方案",
          "slug": "适配方案"
        },
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        },
        {
          "level": 2,
          "title": "vue-router",
          "slug": "vue-router"
        },
        {
          "level": 2,
          "title": "vuex",
          "slug": "vuex"
        },
        {
          "level": 3,
          "title": "1、什么是vuex",
          "slug": "_1、什么是vuex"
        },
        {
          "level": 3,
          "title": "哪种功能场景使用它",
          "slug": "哪种功能场景使用它"
        },
        {
          "level": 3,
          "title": "优势和劣势",
          "slug": "优势和劣势"
        },
        {
          "level": 3,
          "title": "state数据消失的原因",
          "slug": "state数据消失的原因"
        },
        {
          "level": 3,
          "title": "vuex-刷新页面state数据消失（数据持久化）",
          "slug": "vuex-刷新页面state数据消失-数据持久化"
        },
        {
          "level": 3,
          "title": "vuex有哪几种属性？",
          "slug": "vuex有哪几种属性"
        },
        {
          "level": 3,
          "title": "辅助函数",
          "slug": "辅助函数"
        },
        {
          "level": 3,
          "title": "Vuex中解决不同模块命名冲突的问题namespaced: true",
          "slug": "vuex中解决不同模块命名冲突的问题namespaced-true"
        },
        {
          "level": 2,
          "title": "axios",
          "slug": "axios"
        },
        {
          "level": 2,
          "title": "权限管理问题",
          "slug": "权限管理问题"
        },
        {
          "level": 2,
          "title": "优化问题",
          "slug": "优化问题"
        }
      ],
      "lastUpdated": "2022-04-24 1:53:56",
      "lastUpdatedTimestamp": 1650779636000,
      "createdTime": 1650779636000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-09fb61d7",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "pwa",
          "slug": "pwa"
        }
      ],
      "lastUpdated": "2022-04-25 10:04:44",
      "lastUpdatedTimestamp": 1650852284000,
      "createdTime": 1650637376000
    },
    {
      "title": "面向对象",
      "frontmatter": {},
      "regularPath": "/06-js/js%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
      "relativePath": "06-js/js面向对象.md",
      "key": "v-d03e34da",
      "path": "/06-js/js%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
      "headers": [
        {
          "level": 2,
          "title": "一、概念",
          "slug": "一、概念"
        },
        {
          "level": 2,
          "title": "二、创建对象方式",
          "slug": "二、创建对象方式"
        },
        {
          "level": 2,
          "title": "三、操作对象",
          "slug": "三、操作对象"
        },
        {
          "level": 2,
          "title": "四、构造函数",
          "slug": "四、构造函数"
        },
        {
          "level": 3,
          "title": "4.1.new关键字",
          "slug": "_4-1-new关键字"
        },
        {
          "level": 3,
          "title": "4.2.和实例对象的关系",
          "slug": "_4-2-和实例对象的关系"
        },
        {
          "level": 3,
          "title": "4.3.问题",
          "slug": "_4-3-问题"
        },
        {
          "level": 2,
          "title": "五、原型",
          "slug": "五、原型"
        },
        {
          "level": 3,
          "title": "5.1.prototype",
          "slug": "_5-1-prototype"
        },
        {
          "level": 3,
          "title": "5.2.构造函数、实例、原型三者之间的关系",
          "slug": "_5-2-构造函数、实例、原型三者之间的关系"
        },
        {
          "level": 3,
          "title": "5.3.原型链",
          "slug": "_5-3-原型链"
        },
        {
          "level": 3,
          "title": "5.4.原型语法",
          "slug": "_5-4-原型语法"
        },
        {
          "level": 3,
          "title": "5.5.使用建议",
          "slug": "_5-5-使用建议"
        },
        {
          "level": 2,
          "title": "六、继承",
          "slug": "六、继承"
        },
        {
          "level": 3,
          "title": "6.1.原型继承",
          "slug": "_6-1-原型继承"
        },
        {
          "level": 3,
          "title": "6.2.借用构造函数",
          "slug": "_6-2-借用构造函数"
        },
        {
          "level": 3,
          "title": "6.3.组合继承",
          "slug": "_6-3-组合继承"
        },
        {
          "level": 3,
          "title": "6.4.拷贝继承",
          "slug": "_6-4-拷贝继承"
        },
        {
          "level": 2,
          "title": "七、Objece",
          "slug": "七、objece"
        },
        {
          "level": 3,
          "title": "静态成员",
          "slug": "静态成员"
        },
        {
          "level": 3,
          "title": "实例成员",
          "slug": "实例成员"
        }
      ]
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "nav": [
      {
        "text": "05-css",
        "items": [
          {
            "text": "05 Css",
            "link": "/05-css/"
          },
          {
            "text": "DIV水平垂直居中",
            "link": "/05-css/DIV水平垂直居中/"
          }
        ]
      },
      {
        "text": "06-js",
        "items": [
          {
            "text": "00 Es6",
            "link": "/06-js/00-es6/"
          },
          {
            "text": "06 Js",
            "link": "/06-js/"
          }
        ]
      },
      {
        "text": "about",
        "items": [
          {
            "text": "About",
            "link": "/about/"
          }
        ]
      }
    ]
  }
}